### ISSUE TITLE
vertaisarviointi

### ISSUE THREAD

**Issue by MiikaMatias** [tovento/spell-checker#2]
code downloaded 26.02.2022 15:30

-Running the program was fun, I played around with it for some 10 minutes :) 
-Especially interesting was seeing how precisely the program generates suggestions for fixed words; sometimes it seems to accept a word:
![image](https://user-images.githubusercontent.com/100348027/221414630-5b360276-1a63-45cf-aecb-34d28d55df27.png)
but conversely has a very hard time recommending it back:
![image](https://user-images.githubusercontent.com/100348027/221414676-96a8d081-1d89-40f9-8dee-724fce06725b.png)
This is just an interesting note, not a fix suggestion since I think the recommended words are derived in a specific way that stops rare words like 'plymouth' from being recommended. If you have time, could you explain why this is? I couldn't figure it out myself :(

-The project is very clean and very compact, to the extent where maybe it's too compact? From what I saw, the program logic consists of:
damerau_levenshtein.py: 89 lines
trie.py: 37 lines
trie_node.py: 6 lines
check_spelling_service.py: 20 lines
suggest_spelling_service.py: 45 lines
main.py: 31 lines

total: 228 + ui code

In my view this is quite reasonable, and the code is very elegant and the program is easy to understand. However I could maybe understand this being a point of scrutiny for actual evaluators.

-Tests are nicely placed in their own separate section and neatly organized

-Some redundant pycache files seem to exist in some folders; they could be removed

-Otherwise this was a very nice project. I enjoyed reviewing it wholeheartedly!

**Comment by tovento** [comment]
Thank you for the review! :)

Yes, there are some inconsistencies in the app regarding words that are accepted and recommended. I use two lists of English words: 
- First list is used to check if a spelling is acceptable. This list has approximately 350 000 words.
- Second list is used for suggesting correct spellings. For this purpose I wanted a list that is sorted by frequency. If there are many words that have the same Damerau-Levenshtein distance to the original word, I wanted to suggest the more commonly used words first. I was not able to find a sorted list as big as the other one, so I went with a list that has around 40 000 words.

This is why there is a big amount of words that can be accepted (=found in the first list) but will never be recommended to the user (=not found in the second list).
Good that you asked about it, because I should write about this in the documentation!

As for the pycache files, could you specify where you found these? I couldn't spot them myself.
